version: '3'

services:

  db:
    image: postgres:15-alpine
    container_name: spring-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  app:
    build: ./
    container_name: spring-app
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db-data: